- include: openssl.yml

- name: Install dependent packages of nginx
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - gcc
    - gcc-c++
    - pcre-devel
    - zlib-devel
    - libxslt-devel
    - gd-devel

- name: Add nginx user
  user: name=nginx

- name: Check if nginx is installed
  become: no
  ignore_errors: yes
  command: which /usr/sbin/nginx
  register: is_nginx_installed

- name: Download nginx
  get_url: url=https://nginx.org/download/{{ nginx_version }}.tar.gz dest={{ src_path }}
  when: is_nginx_installed | failed

- name: Unpacking nginx.tar.gz
  unarchive: src={{ src_path }}/{{ nginx_version }}.tar.gz dest={{ src_path }} copy=no
  when: is_nginx_installed | failed

- name: Install nginx
  command: "{{ item }} chdir={{ src_path }}/{{ nginx_version }}"
  with_items:
    - ./configure --prefix={{ install_path }}
      --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf
      --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log
      --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock
      --http-client-body-temp-path=/var/cache/nginx/client_temp
      --http-proxy-temp-path=/var/cache/nginx/proxy_temp
      --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
      --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx
      --with-http_realip_module --with-http_addition_module --with-http_sub_module
      --with-http_dav_module --with-http_flv_module --with-http_mp4_module
      --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module
      --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module
      --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail
      --with-http_ssl_module --with-http_v2_module
      --with-openssl={{ src_path }}/{{ openssl_version }}
    - make
    - make install
  when: is_nginx_installed | failed

- name: Set service file
  template: src="nginx.service.j2" dest="/etc/systemd/system/nginx.service"

- name: Exec daemon-reload
  command: systemctl daemon-reload

- name: Set nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Set nginx vimfactory config
  template: src=proxy.conf.j2 dest=/etc/nginx/vimfactory.conf
  notify: restart nginx

- name: Nginx should be starting
  service: name=nginx state=started enabled=yes
