- name: Setting nginx.repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Yum clean all
  command: yum clean all

- name: Install nginx
  yum: name=nginx enablerepo=nginx disablerepo=epel state=latest

- name: Set nginx config
  template: src=proxy.conf.j2 dest=/etc/nginx/conf.d/proxy.conf
  notify: restart nginx

- name: Delete default nginx config
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Nginx should be starting
  service: name=nginx state=started enabled=yes
